// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	productbatch "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/product_batch"
	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pb
func (_m *Services) Create(ctx context.Context, pb productbatch.ProductBatch) (productbatch.ProductBatch, error) {
	ret := _m.Called(ctx, pb)

	var r0 productbatch.ProductBatch
	if rf, ok := ret.Get(0).(func(context.Context, productbatch.ProductBatch) productbatch.ProductBatch); ok {
		r0 = rf(ctx, pb)
	} else {
		r0 = ret.Get(0).(productbatch.ProductBatch)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, productbatch.ProductBatch) error); ok {
		r1 = rf(ctx, pb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Report provides a mock function with given fields: ctx
func (_m *Services) Report(ctx context.Context) ([]productbatch.Report, error) {
	ret := _m.Called(ctx)

	var r0 []productbatch.Report
	if rf, ok := ret.Get(0).(func(context.Context) []productbatch.Report); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]productbatch.Report)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportByID provides a mock function with given fields: ctx, id
func (_m *Services) ReportByID(ctx context.Context, id int) (productbatch.Report, error) {
	ret := _m.Called(ctx, id)

	var r0 productbatch.Report
	if rf, ok := ret.Get(0).(func(context.Context, int) productbatch.Report); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(productbatch.Report)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServices(t mockConstructorTestingTNewServices) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
