// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	productrecord "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/product_record"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]productrecord.ProductRecordGet, error) {
	ret := _m.Called(ctx)

	var r0 []productrecord.ProductRecordGet
	if rf, ok := ret.Get(0).(func(context.Context) []productrecord.ProductRecordGet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]productrecord.ProductRecordGet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Repository) GetById(ctx context.Context, id int) (productrecord.ProductRecordGet, error) {
	ret := _m.Called(ctx, id)

	var r0 productrecord.ProductRecordGet
	if rf, ok := ret.Get(0).(func(context.Context, int) productrecord.ProductRecordGet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(productrecord.ProductRecordGet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, prod
func (_m *Repository) Store(ctx context.Context, prod productrecord.ProductRecord) (productrecord.ProductRecord, error) {
	ret := _m.Called(ctx, prod)

	var r0 productrecord.ProductRecord
	if rf, ok := ret.Get(0).(func(context.Context, productrecord.ProductRecord) productrecord.ProductRecord); ok {
		r0 = rf(ctx, prod)
	} else {
		r0 = ret.Get(0).(productrecord.ProductRecord)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, productrecord.ProductRecord) error); ok {
		r1 = rf(ctx, prod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t NewRepositoryT) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
