version: "3.9"

services:
  mariadb:
    image: mariadb:10.8.3
    container_name: mercadofresco
    hostname: ${DB_HOST}
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/.data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
