// Code generated by mockery v2.13.1. DO NOT EDIT.

package mock_repository

import (
	warehouse "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/warehouse"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateWarehouse provides a mock function with given fields: id, code, address, tel, minCap, minTemp
func (_m *Repository) CreateWarehouse(id int, code string, address string, tel string, minCap int, minTemp int) (warehouse.Warehouse, error) {
	ret := _m.Called(id, code, address, tel, minCap, minTemp)

	var r0 warehouse.Warehouse
	if rf, ok := ret.Get(0).(func(int, string, string, string, int, int) warehouse.Warehouse); ok {
		r0 = rf(id, code, address, tel, minCap, minTemp)
	} else {
		r0 = ret.Get(0).(warehouse.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string, int, int) error); ok {
		r1 = rf(id, code, address, tel, minCap, minTemp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWarehouse provides a mock function with given fields: id
func (_m *Repository) DeleteWarehouse(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() []warehouse.Warehouse {
	ret := _m.Called()

	var r0 []warehouse.Warehouse
	if rf, ok := ret.Get(0).(func() []warehouse.Warehouse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]warehouse.Warehouse)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id int) (warehouse.Warehouse, error) {
	ret := _m.Called(id)

	var r0 warehouse.Warehouse
	if rf, ok := ret.Get(0).(func(int) warehouse.Warehouse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(warehouse.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementID provides a mock function with given fields:
func (_m *Repository) IncrementID() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UpdatedWarehouseID provides a mock function with given fields: id, code
func (_m *Repository) UpdatedWarehouseID(id int, code string) (warehouse.Warehouse, error) {
	ret := _m.Called(id, code)

	var r0 warehouse.Warehouse
	if rf, ok := ret.Get(0).(func(int, string) warehouse.Warehouse); ok {
		r0 = rf(id, code)
	} else {
		r0 = ret.Get(0).(warehouse.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(id, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
