// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	buyer "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/buyer"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: cardNumberId, firstName, lastName
func (_m *Service) Create(cardNumberId string, firstName string, lastName string) (buyer.Buyer, error) {
	ret := _m.Called(cardNumberId, firstName, lastName)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(string, string, string) buyer.Buyer); ok {
		r0 = rf(cardNumberId, firstName, lastName)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(cardNumberId, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]buyer.Buyer, error) {
	ret := _m.Called()

	var r0 []buyer.Buyer
	if rf, ok := ret.Get(0).(func() []buyer.Buyer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]buyer.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Service) GetById(id int) (buyer.Buyer, error) {
	ret := _m.Called(id)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(int) buyer.Buyer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, cardNumberId, firstName, lastName
func (_m *Service) Update(id int, cardNumberId string, firstName string, lastName string) (buyer.Buyer, error) {
	ret := _m.Called(id, cardNumberId, firstName, lastName)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(int, string, string, string) buyer.Buyer); ok {
		r0 = rf(id, cardNumberId, firstName, lastName)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string) error); ok {
		r1 = rf(id, cardNumberId, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewServiceT interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t NewServiceT) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
