// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	seller "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/seller"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the MockRepository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: cid, companyName, address, telephone
func (_m *MockRepository) Create(cid int, companyName string, address string, telephone string) (seller.Seller, error) {
	ret := _m.Called(cid, companyName, address, telephone)

	var r0 seller.Seller
	if rf, ok := ret.Get(0).(func(int, string, string, string) seller.Seller); ok {
		r0 = rf(cid, companyName, address, telephone)
	} else {
		r0 = ret.Get(0).(seller.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string) error); ok {
		r1 = rf(cid, companyName, address, telephone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *MockRepository) GetAll() ([]seller.Seller, error) {
	ret := _m.Called()

	var r0 []seller.Seller
	if rf, ok := ret.Get(0).(func() []seller.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]seller.Seller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *MockRepository) GetOne(id int) (seller.Seller, error) {
	ret := _m.Called(id)

	var r0 seller.Seller
	if rf, ok := ret.Get(0).(func(int) seller.Seller); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(seller.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: cid, companyName, address, telephone, _a4
func (_m *MockRepository) Update(cid int, companyName string, address string, telephone string, _a4 seller.Seller) (seller.Seller, error) {
	ret := _m.Called(cid, companyName, address, telephone, _a4)

	var r0 seller.Seller
	if rf, ok := ret.Get(0).(func(int, string, string, string, seller.Seller) seller.Seller); ok {
		r0 = rf(cid, companyName, address, telephone, _a4)
	} else {
		r0 = ret.Get(0).(seller.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string, seller.Seller) error); ok {
		r1 = rf(cid, companyName, address, telephone, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
