// Code generated by mockery v2.13.1. DO NOT EDIT.

package mock_service_carry

import (
	domain "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/carry/domain"
	mock "github.com/stretchr/testify/mock"
)

// ServiceCarry is an autogenerated mock type for the ServiceCarry type
type ServiceCarry struct {
	mock.Mock
}

// CreateCarry provides a mock function with given fields: carry
func (_m *ServiceCarry) CreateCarry(carry domain.Carry) (domain.Carry, error) {
	ret := _m.Called(carry)

	var r0 domain.Carry
	if rf, ok := ret.Get(0).(func(domain.Carry) domain.Carry); ok {
		r0 = rf(carry)
	} else {
		r0 = ret.Get(0).(domain.Carry)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Carry) error); ok {
		r1 = rf(carry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServiceCarry interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceCarry creates a new instance of ServiceCarry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceCarry(t mockConstructorTestingTNewServiceCarry) *ServiceCarry {
	mock := &ServiceCarry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
