name: Go Test
on:
  push:
    branches: [ "feature-product-4" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: go test -v ./...