// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	products "github.com/Gopher-Rangers/mercadofresco-gopherrangers/internal/product"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckProductCode provides a mock function with given fields: id, productCode
func (_m *Repository) CheckProductCode(id int, productCode string) bool {
	ret := _m.Called(id, productCode)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, string) bool); ok {
		r0 = rf(id, productCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]products.Product, error) {
	ret := _m.Called(ctx)

	var r0 []products.Product
	if rf, ok := ret.Get(0).(func(context.Context) []products.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Repository) GetById(ctx context.Context, id int) (products.Product, error) {
	ret := _m.Called(ctx, id)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(context.Context, int) products.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, prod
func (_m *Repository) Store(ctx context.Context, prod products.Product) (products.Product, error) {
	ret := _m.Called(ctx, prod)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(context.Context, products.Product) products.Product); ok {
		r0 = rf(ctx, prod)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, products.Product) error); ok {
		r1 = rf(ctx, prod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, prod, id
func (_m *Repository) Update(ctx context.Context, prod products.Product, id int) (products.Product, error) {
	ret := _m.Called(ctx, prod, id)

	var r0 products.Product
	if rf, ok := ret.Get(0).(func(context.Context, products.Product, int) products.Product); ok {
		r0 = rf(ctx, prod, id)
	} else {
		r0 = ret.Get(0).(products.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, products.Product, int) error); ok {
		r1 = rf(ctx, prod, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t NewRepositoryT) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
